name: af
channels:
  # - conda-forge
  - pytorch
  - defaults
dependencies:
  - python
  - cudatoolkit=11.3
  - pytorch
  - torchvision
  - torchaudio
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - pip
  - pip:
    - neptune-client
    - entmax
#    - torch==1.9.0
